# Generated by Django 3.2.8 on 2021-10-18 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211016_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='pic',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
