# Generated by Django 3.2.8 on 2021-10-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='desc_short',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
